config/routes.rb
Deposits::Application.routes.draw do
  devise_for :users

  get "holders/index"

  get "banks/index"

  get "fdrs/index"

  get "fdr/index"

      resources :fdrs
match 'fdrs/:id/destroy' => 'fdrs#destroy', :as => :destroy    	

   root :to => "fdrs#index"

end

app/models/bank.rb
# == Schema Information
# Schema version: 20110620132445
#
# Table name: banks
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Bank < ActiveRecord::Base
 has_many :fdrs
end

app/models/fdr.rb
# == Schema Information
# Schema version: 20110620132445
#
# Table name: fdrs
#
#  id         :integer(4)      not null, primary key
#  amount     :decimal(10, 2)  default(0.0)
#  m_amount   :decimal(10, 2)  default(0.0)
#  s_date     :date
#  m_date     :date
#  r_no       :string(255)
#  bank_id    :integer(10)
#  created_at :datetime
#  updated_at :datetime
#

class Fdr < ActiveRecord::Base
 has_and_belongs_to_many :holders
belongs_to :bank

validates_presence_of :amount, :m_amount,:s_date,:m_date,:r_no  
validates_uniqueness_of :r_no

end

app/models/holder.rb
# == Schema Information
# Schema version: 20110620132445
#
# Table name: holders
#
#  id         :integer(4)      not null, primary key
#  f_name     :string(255)
#  l_name     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Holder < ActiveRecord::Base
 has_and_belongs_to_many :fdrs
def full_name

"#{f_name} #{l_name}"
end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  def index
  end
def get_name
@bank = Bank.new
return @bank.name

end


end

app/controllers/fdr_controller.rb
class FdrController < ApplicationController
  def index

@fdrs = Fdr.find(:all) 
  end

end

app/controllers/fdrs_controller.rb
class FdrsController < ApplicationController
before_filter :authenticate_user!, :except => [:some_action_without_auth]

  def index
@fdrs = Fdr.find(:all)	
  end

def new
@fdr = Fdr.new
@h  = Holder.find(:all)
@b  = Bank.find(:all)

end

def create
@fdr = Fdr.new(params[:fdr])
@b  = Bank.find(:all)
@h  = Holder.find(:all)
if @fdr.save
flash[:notice] = 'FDR submissision succeeded'
redirect_to fdrs_path

else
render :action =>  'new'
end


end


def destroy
 Fdr.find(params[:id]).destroy
redirect_to fdrs_path

end
def show
redirect_to fdrs_path
end

end

app/controllers/holders_controller.rb
class HoldersController < ApplicationController
  def index
  end
def full_name

"#{f_name}.#{l_name}"
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/fdr_helper.rb
module FdrHelper
end

app/helpers/fdrs_helper.rb
module FdrsHelper
end

app/helpers/holders_helper.rb
module HoldersHelper
end

app/views/banks/index.html.erb
<h1>Banks#index</h1>
<p>Find me in app/views/banks/index.html.erb</p>

app/views/fdr/index.html.erb
<table>
<tr><th>Amount</th><th>Maturity Amt.</th><th>Holders</th><th>Bank</th><th><Start Date</th><th>Maturity Date</th></tr>
<%= for fdr in @fdrs %>
<tr>
<td><%= fdr.amount %></td>
<td><%= fdr.m_amount %></td>
<td><%= fdr.holders.f_name +' '+ fdr.holders.l_name  %></td>
<td><%= fdr.bank %></td>
<td><%= fdr.s_date %></td>
<td><%= fdr.m_date %></td>
</tr>
<% end  %>

</table>

app/views/fdrs/create.html.erb
<p> New FD added to the data base </p>

app/views/fdrs/index.html.erb
<h1> <center>Record of Fixed Deposit Receipts</center></h1><hr>
<table border=1px>
<tr>
<th>Receipt No.</th>
<th>Start_date</th>
<th>Amount</th>
<th>Mat_Amt.</th>
<th>Holders</th>
<th>Bank</th>

<th>Mat_Date</th>
</tr>
<% for fdr in @fdrs %>
<tr>
<td><%= fdr.r_no %>
<td><%= fdr.s_date %></td>
<td><%= fdr.amount %></td>
<td><%= fdr.m_amount %></td>
<td><% for z in fdr.holders %>
<%= z[:f_name] + z[:l_name] %>,
<% end %>

</td>

<td>
<%=h fdr.bank.name  %>

</td>

<td><%= fdr.m_date %></td>

<td><%= link_to 'delete', destroy_path(fdr),:confirm => 'Are you sure?' %></td>
</tr>
<% end  %>
i</table>

app/views/fdrs/new.html.erb
<%= error_messages_for 'fdr' %>

<% form_for @fdr  do |f| %>
<p>Bank <br />

<%= collection_select("fdr", :bank_id, @b , "id",:name , :prompt => true)%>

</p>
<p>Select Holders:<br />

<%  for holder in @h %>
         <%= check_box_tag "fdr[holder_ids][]", "#{holder.id}",@fdr.holders.include?(holder) %> 
         <%= "#{holder.full_name}" -%>




<% end %>
</p>
<p>
Receipt No:<br />
<%= f.text_field :r_no%>
</p>

<p>
Amount <br />
<%= f.text_field :amount %>
</p>
<p>
<p>
Start Date:<br />
<%= f.text_field :s_date %>

</p>
<p>
Date of Maturity<br />
<%= f.text_field :m_date %>
</p>
Maturity Amount:<br />
<%= f.text_field :m_amount %>

</p>



<p>
<%= submit_tag %>
</p>
<% end %>

app/views/holders/index.html.erb
<h1>Holders#index</h1>
<p>Find me in app/views/holders/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-type"
content="text/html; charset=utf-8" />
<title>Fixed Deposits</title>
<%= stylesheet_link_tag 'style' %>
</head>
<body>
<div id="content">
<h1>Epic Deposits Manager</h1>
<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= uname=current_user.email.split('@');uname[0] %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

<% unless flash[:notice].blank? %>
<div id="notification"><%= flash[:notice] %></div>
<% end %>
<p class="notice"></p>
<p class="alert"><%= alert %></p>

<%= yield %>
<%= link_to "New FDR",  new_fdr_path %>
<%= link_to "List of FDs", fdrs_index_path %>
</div>
</body>
</html>